version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-hola-mundo
    ports:
      - "80:80"
    volumes:
      - ./TAREA 2:/app/src
    environment:
      - NODE_ENV=development